name: parse_server_sdk_flutter
description: Flutter plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 2.1.0
homepage: https://github.com/phillwiggins/flutter_parse_sdk

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk:
    path: "../dart"

  # Networking
  connectivity: ^3.0.3 # only used in the flutter part
  dio: ^4.0.0
  #Database
  shared_preferences: ^2.0.5 # only used in the flutter part

  # Utils
  path_provider: ^2.0.1 # only used in the flutter part
  package_info: ^0.4.3+4 # only used in the flutter part
  sembast: ^3.0.0+4 # required for transitive use only
  path: ^1.8.0 # required for transitive use only

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  mockito: ^4.1.4

environment:
  sdk: '>=2.10.0 <3.0.0'